CREATE TABLE cliente (
  id INT NOT NULL PRIMARY KEY auto_increment,
  nome VARCHAR (255) NOT NULL,
  cpf VARCHAR (14) NOT NULL,
  nascimento DATE NOT NULL ,
  telefone VARCHAR(11) NOT NULL,
  email VARCHAR (255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
