CREATE TABLE carro (
  id INT NOT NULL PRIMARY KEY auto_increment,
  nome VARCHAR (100) NOT NULL DEFAULT '',
  marca VARCHAR (50) NOT NULL DEFAULT '',
  categoria INT NOT NULL,
  ano VARCHAR (4) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=latin1;